spring:
  application:
    name: authentication-server
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${server.port}:${random.value}
      host: localhost
      port: 8500

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
 
logging.level:
    org.springframework.cloud:
      consul: DEBUG