spring:
    application:
        name: gateway-server
    cloud:
        consul:
            enabled: true
            discovery:
                enabled: true
                register: true
                deregister: false
                instanceId: ${spring.application.name}:${server.port}:${random.value}
            host: localhost
            port: 8500

server:
    port: 8081
    address: 0.0.0.0

camel:
    cloud:
        consul:
            service-discovery:
                enabled: true
                url: http://localhost:8500
        service-call:
            component: undertow
    rest:
        component: servlet
        binding-mode: auto
    component:
        servlet:
            mapping:
                context-path: /services/api/*
        properties:
            auto-discover-properties-sources: true

management:
    endpoints:
        web:
            exposure:
                include: "*"

logging.level:
    org.springframework.cloud:
        consul: DEBUG